//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Distribution
{
    public int idDistr { get; set; }
    public Nullable<int> idRailway { get; set; }
    public Nullable<int> idBranch { get; set; }

    public virtual Branches Branches { get; set; }
}
